config/routes.rb
Rails.application.routes.draw do
  root 'landers#land'
  get '/about', to: 'landers#about'

  resources :people
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :person

  validates :age, numericality: true
end

app/models/person.rb
class Person < ApplicationRecord
  # Rails Association
  has_many :dogs, dependent: :destroy

  # Validation
  validates :age, numericality: true
  validates :first_name, :last_name, :age, presence: true
  validates :gender, inclusion: { in: %w(Male Female Other), message: "is not a valid option \nAllowed genders are male, female, or other" }
  
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  
  def index
    @dogs = Dog.all.order(:id)
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to people_path 
    else
      render :new
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
  
    if @dog.update(dog_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def delete
    Dog.find(params[:id]).destroy
    redirect_to people_path
  end

  private

  def dog_params
    params.require(:dog).permit(:animal_name, :breed, :age, :person_id)
  end
end

app/controllers/landers_controller.rb
class LandersController < ApplicationController
  def land
  end

  def about
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all.order(:id)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to new_dog_path 
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
  
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def delete
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
    def person_params
      params.require(:person).permit(:first_name, :last_name, :age, :gender)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/landers_helper.rb
module LandersHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dogs/edit.html.erb
<h1>Edit Dog Form</h1>
<%= form_for @dog do |f| %>
    <%= f.label :animal_name %>
    <%= f.text_field :animal_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :breed %>
    <%= f.text_field :breed %>

    <%= f.label :person_id %>
    <%= f.text_field :person_id %>

    <%= f.submit %>

    <% end %>

app/views/dogs/index.html.erb
<h1>The Doggos!</h1>
<p><% @dogs.each do |dog| %></p>
<h3><%= dog.animal_name %></h3>
<%= link_to "View Dog Details", dog_path(dog.id) %>
<%= link_to "Edit Dog Details", edit_dog_path(dog.id) %>
<%= link_to 'Destroy Dog', dog, method: :delete %>
</br>
<% end  %>

<%= link_to "New Dog",  new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog Form</h1>
<%= form_for @dog do |f| %>
    <%= f.label :animal_name %>
    <%= f.text_field :animal_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :breed %>
    <%= f.text_field :breed %>

    <%= f.label :person_id %>
    <%= f.text_field :person_id %>

    <%= f.submit %>

    <% end %>

app/views/dogs/show.html.erb
<h1>Dog: <%= @dog.animal_name %></h1>
<p>Breed: <%= @dog.breed %> </p>
<p>Age: <%= @dog.age %></p>
<p>Owner: <%= @dog.person.full_name %><p>
</br>
</br>
<%= link_to "Back", dogs_path %>

app/views/landers/about.html.erb
<h1>This is the about page!</h1>
<p>Nothing much to here. Just an empty page.</p>

app/views/landers/land.html.erb
<h1>Welcome to your landing page!</h1>
<p>This app is all about owners and their dogs!</p>
<p>Click a link above to start exploring!</p>

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path%>
<%= link_to "About", about_path%>
<%= link_to "People", people_path%>
<%= link_to "Dogs", dogs_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person Form</h1>
<%= form_for @person do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.submit %>

    <% end %>

app/views/people/index.html.erb
<h1>People and Their Dog(s)</h1>
<p><% @people.each do |person| %></p>
<h2><%= person.full_name %></h2>
<%= link_to "View Person Details", person_path(person.id) %>
<%= link_to "Edit Person Details", edit_person_path(person.id) %>
<%= link_to 'Destroy Person', person, method: :delete %>
</br>
<% person.dogs.each do |dog| %>
<h3><%= dog.animal_name %></h3>
<%= link_to "View Dog Details", dog_path(dog.id) %>
<%= link_to "Edit Dog Details", edit_dog_path(dog.id) %>
<%= link_to 'Destroy Dog', dog, method: :delete %>
</br>
<% end  %>
<% end  %>

<%= link_to "New Person", new_person_path %>
<%= link_to "New Dog",  new_dog_path %>

app/views/people/new.html.erb
<h1>New Person Form</h1>
<%= form_for @person do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.label :gender %>
    <%= f.text_field :gender %>

    <%= f.submit %>

    <% end %>

app/views/people/show.html.erb
<h1>Person: <%= @person.full_name %></h1>
<%= @person.age %>
<%= @person.gender %>
</br>
<% @person.dogs.each do |dog| %>
<h3><%= dog.animal_name %></h3>
<p> breed: <%= dog.breed %>. Age: <%= dog.age %> </p>
<%end%>
</br>
</br>
<%= link_to "Back", people_path %>